In [1]:
from pandas_datareader import data, wb
import numpy as np


In [ ]:

start = datetime.datetime(2010, 1, 1)
end = datetime.datetime(2017, 1, 1)
df = data.get_data_yahoo('MS', start, end)

### .where 

In [ ]:
df["equal"] = np.where((df.High == df.Low), True, False)
df.head()

In [9]:
a = np.linspace(0,2,9)
a

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [10]:
b = np.linspace(1,3,9)
b

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [8]:
a+b

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])