In [2]:
from pandas_datareader import data, wb
import numpy as np


In [ ]:

start = datetime.datetime(2010, 1, 1)
end = datetime.datetime(2017, 1, 1)
df = data.get_data_yahoo('MS', start, end)

### .where 

In [ ]:
df["equal"] = np.where((df.High == df.Low), True, False)
df.head()

In [9]:
a = np.linspace(0,2,9)
a

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [10]:
b = np.linspace(1,3,9)
b

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [8]:
a+b

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

### a very easy way to check whether to ndarray has same values

In [ ]:
a1 = [0,1,1,2]
a2=[0,1,2,2]
np.allclose(a1,a2)

In [2]:
import numpy as np

In [4]:
np.zeros((3,3), dtype=np.float64,order='C')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
c=np.array([[1,1,1],
           [2,2,2],
           [3,3,3]],order='C')

In [6]:
f=np.array([[1,1,1],
           [2,2,2],
           [3,3,3]],order='F')

In [7]:
x=np.random.standard_normal((3,1500000))
c=np.array(x,order='C')
f=np.array(x,order='F')
x=0.0

### setfiff1d()

In [3]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
np.setdiff1d(a, b)
# array([1, 2])

array([1, 2])

### intersect1d()

In [4]:
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])
# array([1, 3])

array([1, 3])